<a href="https://colab.research.google.com/github/bichu136/CS114.L11.KHCL/blob/master/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification

mong muốn của bài toán phân loại là bài toán mà đầu ra của chúng ta là 0 hoặc 1, với:
- 0 biểu thị cho sự vắn mặt, ko hiển thị của tính chất mà chúng ta đang xét ở input đầu vào 
- 1 biểu thị cho sự hiện diện của 1 tính chất mà chúng ta đang xét ở input đầu vào.

=>Từ đó ta có thể nói được rằng input của bài toán này có thuộc lớp phân loại đang xét hay không.

## Logistic regression

1. ### sigmoid function(logistic function)
Ứng với mỗi $x \in R$  là đầu vào của hàm thì hàm này sẽ có dạng.<br>
![alt text](https://qph.fs.quoracdn.net/main-qimg-6b67bea3311c3429bfb34b6b1737fe0c)<br>
<br>
Có vẻ gần giống với mong muốn của bài toán.<br>

#### Cho rằng:
- y=1 nếu như $\sigma(x)\geq 0.5$ => $x\geq0$
- y=0 nếu như $\sigma(x)< 0.5$ => $x<0$
2. ### Decision boundary 
Như đã nói ở trên, việc phân lớp chỉ còn lại là tìm ra đầu vào cho sigmoid function thông qua dữ liệu đầu vào thật sự của bài toán phân lớp $X=\{x_1,x_2,x_3,...,x_n\}$. với n là số chiều của dữ liệu. <br>
=> ta có thể kiếm 1 đường thẳng sao cho $f_\theta(X)=\theta^T X$ 
thì đường thẳng đó có thể chia dữ liệu ra làm 2 phần.<br><br>
Hàm tổng quát cho bài toán $\sigma(f_\theta(X)) = h_\theta(X)$ 
![alt text](https://www.shuhanyu.com/2018/07/08/MLofLogisticRegressionWithDecisionBoundary/DecisionBoundary.png)<br>
3. ### Cost function
  với bộ dữ liệu cho trước $D={(X_1,y_1),....(X_k,y_k)}$ với k là số lượng dòng dữ liệu. <br>
  $$cost(X,y)=
  \begin{Bmatrix}
  -log(h_\theta(X))&với\ y=1\\
  -log(1-h_\theta(X))&với\ y=0
  \end{Bmatrix}
  $$
  và để dễ dàng tính toán, ta có thể viết.
  $$
  cost(X,y)=-(ylog(h_\theta(X)) +(1-y)log(1-h_\theta(X)))
  $$
4. ### Gradient Descent
giống như mục tiêu của Linear Regression, mục tiêu mà chúng ta nhắm đến là means của Cost function trên tập dữ liệu là nhỏ nhất.
$$
minJ(\theta) = \frac{1}{k}\sum_{i=1}^{k}cost(X_i,y_i)=\frac{1}{k}\sum_{i=1}^{k}(ylog(h_\theta(X)) +(1-y)log(1-h_\theta(X)))
$$
áp dụng thuật toán linear regression
repeat{<br>
$$ \theta_j:=\theta $$
<br>
}

## Code mẫu của scikit-learn

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
import pandas as pd
import sys

sys.setrecursionlimit(99999)

In [ ]:
!cat fetal_health.csv

In [ ]:
# import data
data = pd.read_csv('fetal_health.csv')
data = np.array(data)
X = data[:, :-1]
Y = data[:, -1:]

split = len(X)//2
X_train = X[:-split]
Y_train = Y[:-split]

X_test = X[-split:]
Y_test = Y[-split:]

print(len(X_test))
print(len(X))

In [ ]:
print(type(X_train))
print(Y_train.shape)

<class 'numpy.ndarray'>
(1063, 1)


In [ ]:
print(X)
print(Y)

[[1.20e+02 0.00e+00 0.00e+00 ... 1.21e+02 7.30e+01 1.00e+00]
 [1.32e+02 6.00e-03 0.00e+00 ... 1.40e+02 1.20e+01 0.00e+00]
 [1.33e+02 3.00e-03 0.00e+00 ... 1.38e+02 1.30e+01 0.00e+00]
 ...
 [1.40e+02 1.00e-03 0.00e+00 ... 1.52e+02 4.00e+00 1.00e+00]
 [1.40e+02 1.00e-03 0.00e+00 ... 1.51e+02 4.00e+00 1.00e+00]
 [1.42e+02 2.00e-03 2.00e-03 ... 1.45e+02 1.00e+00 0.00e+00]]
[[2.]
 [1.]
 [1.]
 ...
 [2.]
 [2.]
 [1.]]


In [ ]:
logreg = LogisticRegression(max_iter=99999)

# Create an instance of Logistic Regression Classifier and fit the data.
logreg.fit(X_train, Y_train.ravel())

Y_pred = logreg.predict(X_test)
print(Y_pred)

In [ ]:
print(Y_test)

In [ ]:
confusion_table = np.zeros((3,3))

for i in range(len(Y_pred)):
  confusion_table[int(Y_pred[i]) - 1][int(Y_test[i]) - 1] += 1

print(confusion_table)

In [ ]:
# Plot the decision boundary. For that, we will assign a color to each
# point in the mesh [x_min, x_max]x[y_min, y_max].
x_min, x_max = X[:, 0].min() - .5, X[:, 0].max() + .5
y_min, y_max = X[:, 1].min() - .5, X[:, 1].max() + .5
h = .02  # step size in the mesh
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
Z = logreg.predict(np.c_[xx.ravel(), yy.ravel()])

# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure(1, figsize=(4, 3))
plt.pcolormesh(xx, yy, Z, cmap=plt.cm.Paired)

# Plot also the training points
plt.scatter(X[:, 0], X[:, 1], c=Y, edgecolors='k', cmap=plt.cm.Paired)
plt.xlabel('Sepal length')
plt.ylabel('Sepal width')

plt.xlim(xx.min(), xx.max())
plt.ylim(yy.min(), yy.max())
plt.xticks(())
plt.yticks(())

plt.show()